### ISSUE TITLE
[Bug] LFG isn't skinned (as a lot of others) and doesn't show roles (tank/healer/DPS) anymore

### ISSUE THREAD

**Issue by Heregellas** [Gethe/Aurora#94]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Client

Retail

### Current Behavior

The frame isn't skinned & the roles are not showing, as you can see on this screenshot :

https://i.gyazo.com/60d579e992a7e3143ef67e159a683622.png

Which makes it super confusing when tagging in a group :p

**Comment by Linktotherescue** [comment]
Is a new version for patch 10.1 being worked on to fix all fo the LUA errors and skinning? Any update would be appreciated.

**Comment by Heregellas** [comment]
No news at all since weeks (including on the various topics regarding lua issues & stuff since this add-on is basically broken since the patch) yeah :/
Not the first time it happened tbf, will probably check for some substitute on my end

**Comment by Linktotherescue** [comment]
Well, the last update was 5/3. It usually takes a couple of weeks after a major patch for a new version to become available. 

I just apprecaite the owner of the app keeping it up to date. I struggle to use the default UI becuase everything is so ugly. I would just say be patient. Hopefully they are just working out some of the coding stuff due to 10.1

**Comment by shfthappens** [comment]
I am also struggling with the default UI. Have resorted to skinner and changing some settings to make it look as close to aurora as possible but it isnt quite there....
